<template>
  <div>
    <div class="grid grid-cols-6 gap-3">
      <div v-for="(el, ind) in icons" class="flex">
        <Icons :key="ind" :name="el.name" color="red" size="24" />
        <span class="mx-2"> - </span>
        <span
          @click="copy(el.name)"
          class="font-mono cursor-pointer hover:text-cyan-900"
        >
          {{ el.name }}</span
        >
      </div>
    </div>
  </div>
</template>

<script setup>
const copy = (text) => {
  navigator.clipboard.writeText(text);
};

const icons = ref([
  { name: "arrow_back" },
  { name: "arrow_forward" },
  { name: "chevron_left" },
  { name: "chevron_right" },
  { name: "expand_more" },
  { name: "expand_less" },
  { name: "unfold_less" },
  { name: "unfold_more" },
  { name: "clear" },
  { name: "add" },
  { name: "remove" },
  { name: "check" },
  { name: "done_all" },
  { name: "playlist_add" },
  { name: "sort" },
  { name: "filter_list" },
  { name: "home" },
  { name: "arrow_drop_down" },
  { name: "arrow_right" },
  { name: "filter_alt" },
  { name: "more_vert" },
  { name: "more_horiz" },
  { name: "menu" },
  { name: "backspace" },
  { name: "send" },
  { name: "delete_outline" },
  { name: "create" },
  { name: "settings" },
  { name: "account_circle" },
  { name: "person" },
  { name: "person_add_alt" },
  { name: "people_alt" },
  { name: "add_box" },
  { name: "add_circle_outline" },
  { name: "add_circle" },
  { name: "remove_circle" },
  { name: "schedule" },
  { name: "event" },
  { name: "calendar_today" },
  { name: "search" },
  { name: "file_download" },
  { name: "cached" },
  { name: "cloud_upload" },
  { name: "upload" },
  { name: "favorite_border" },
  { name: "favorite" },
  { name: "star_border" },
  { name: "star" },
  { name: "star_half" },
  { name: "list" },
  { name: "gridview" },
  { name: "listview" },
  { name: "play_circle_filled" },
  { name: "pause" },
  { name: "play_circle" },
  { name: "pause_circle_outline" },
  { name: "play_arrow" },
  { name: "textsms" },
  { name: "mark_email_unread" },
  { name: "message" },
  { name: "drafts" },
  { name: "email" },
  { name: "chat_bubble_outline" },
  { name: "chat" },
  { name: "mark_unread_chat_alt" },
  { name: "comment" },
  { name: "call" },
  { name: "sticky_note_2" },
  { name: "description" },
  { name: "add_card" },
  { name: "credit_card" },
  { name: "notifications_active" },
  { name: "dashboard" },
  { name: "grid_view" },
  { name: "inbox" },
  { name: "folder" },
  { name: "folder_open" },
  { name: "folder_copy" },
  { name: "create_new_folder" },
  { name: "content_paste" },
  { name: "cloud_queue" },
  { name: "cloud_off" },
  { name: "visibility_off" },
  { name: "local_offer" },
  { name: "mark_unread_chat_alt" },
  { name: "history" },
  { name: "photo_camera" },
  { name: "photo" },
  { name: "mic" },
  { name: "archive" },
  { name: "flag" },
  { name: "alarm" },
  { name: "fullscreen" },
  { name: "map" },
  { name: "gps_fixed" },
  { name: "gps_not_fixed" },
  { name: "error" },
  { name: "help" },
  { name: "error_outline" },
  { name: "help_outline" },
  { name: "warning" },
  { name: "live_help" },
  { name: "dark_mode" },
  { name: "security" },
  { name: "verified_user" },
  { name: "poll" },
  { name: "verified" },
  { name: "block" },
  { name: "thumb_up" },
  { name: "thumb_down_off_alt" },
  { name: "warning_amber" },
  { name: "g_translate" },
  { name: "language" },
  { name: "hourglass_empty" },
  { name: "link" },
  { name: "notifications_none" },
  { name: "not_listed_location" },
  { name: "fmd_good" },
  { name: "shopping_basket" },
  { name: "inventory_2" },
  { name: "shopping_cart" },
  { name: "headphones" },
  { name: "shopping_bag" },
  { name: "account_balance_wallet" },
  { name: "phone_enabled" },
  { name: "content_paste_search" },
  { name: "print" },
  { name: "desktop_mac" },
  { name: "cloud_download" },
  { name: "business" },
  { name: "laptop_windows" },
  { name: "headset_mic" },
  { name: "store" },
  { name: "account_balance" },
  { name: "vpn_key" },
  { name: "lock_open" },
  { name: "lock" },
  { name: "task_alt" },
  { name: "language" },
  { name: "check_filled" },
  { name: "facebook" },
  { name: "twitter" },
  { name: "linkedin" },
  { name: "instagram" },
  { name: "whatsapp" },
  { name: "youtube" },
  { name: "facebook_2" },
  { name: "twitter_2" },
  { name: "linkedin_2" },
  { name: "instagram_2" },
  { name: "whatsapp_2" },
  { name: "youtube_2" },
  { name: "facebook_3" },
  { name: "twitter_3" },
  { name: "linkedin_3" },
  { name: "instagram_3" },
  { name: "whatsapp_3" },
  { name: "youtube_3" },
  { name: "person_fill" },
  { name: "chat_fill" },
  { name: "shopping_cart_fill" },
  { name: "lock_fill" },
  { name: "deliery" },
  { name: "ae" },
  { name: "au" },
  { name: "cn" },
  { name: "de" },
  { name: "dk" },
  { name: "fr" },
  { name: "gb" },
  { name: "it" },
  { name: "ru" },
  { name: "us" },
]);
</script>

<style lang="scss" scoped></style>